config/routes.rb
Socialplanner::Application.routes.draw do
  root :to => 'events#index'

  resources :events
  resources :users, :only => [:new]

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'register', to: 'sessions#new', as: 'register'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'settings', to: 'users#edit', as: 'settings'
  match 'delete_account', to: 'users#destroy', as: 'delete_account'
end

app/models/acceptable_invite.rb
class AcceptableInvite < ActiveRecord::Base
  attr_accessible :event_id, :fb_id, :state, :name
  belongs_to :event

  validate :state, :inclusion => {:in => %w(pending noreply attending maybe declined expired)}

  before_create do
    self.state = 'pending'
  end

  def self.with_state(state)
    where(:state => state)
  end

  def self.pending
    with_state('pending')
  end

  def self.noreply #sent out invite
    with_state('noreply')
  end

  # Facebook calls the states attending, maybe, and declined
  def self.attending
    with_state('attending')
  end

  def self.declined
    with_state('declined')
  end

  def self.maybe
    with_state('maybe')
  end

  def self.expired
    with_state('expired')
  end

  def noreply!
    update_attributes(:state => 'noreply')
  end

  def attending!
    update_attributes(:state => 'attending')
  end

  def declined!
    update_attributes(:state => 'declined')
  end

  def maybe!
    update_attributes(:state => 'maybe')
  end

  def expired!
    update_attributes(:state => 'expired')
  end

  def set_state(state)
    update_attributes(:state => state)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  before_save :convert_minutes_to_seconds
  attr_accessible :id, :created_at, :updated_at, :name, :description,
                  :creator_id, :start_datetime, :end_datetime, :location,
                  :headcount, :private, :invitees_info,
                  :fb_id, :invited, :expired_time

  validates :name, :presence => true
  validates :creator, :presence => true

  validates :start_datetime, :presence => true
  validates_datetime :end_datetime, :after => :start_datetime, :after_message => "must be set a time after event start time"
  
  validates :end_datetime, :presence => true
  validates_datetime :start_datetime, :after => lambda { 1.hour.from_now }, :after_message => "must be at least an hour from now"

  validates :headcount, :numericality => { :greater_than => 0, :only_integer => true }
  validates :expired_time, :presence => true, :numericality => { :only_integer => true }

  belongs_to :creator, :class_name => "User"

  has_many :acceptable_invites, dependent: :destroy

  def invitees_info=(invitees_info)
    # If we ever need to append rather than re-assign the invites
    # this will be a problem.  But for now, once we choose who to invite
    # we never go back.  Save that shit for v2.

    self.acceptable_invites = invitees_info.map do |invitee_info|
      info = invitee_info.split(",")
      AcceptableInvite.new(:fb_id => info.first, :name => info.last.strip)
    end
  end
  
  def convert_minutes_to_seconds
    self.expired_time *= 60
  end
  
  def in_progress?
    if (self.acceptable_invites.attending.count < self.headcount) && (self.start_datetime > Time.now)
     #hasn't reached max goal and still is in the future
      true
    else
      false
    end
  end

  def full?
    if self.acceptable_invites.attending >= self.headcount
      true
    else
      false
    end
  end

  def self.tracked #events that are to be tracked by the background processes
    all_events = Event.all
    tracking = []
    all_events.each do |event|
      if event.in_progress?
        tracking << event
      end
    end
    tracking
  end

  def to_facebook_params
    facebook_params = {
        :name => self.name,
        :description => self.description,
        :start_time => self.start_datetime,
        :end_time => self.end_datetime,
        :location => self.location,
        :privacy_type => 'SECRET'
    }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid

  validates :name, :presence => true
  validates :oauth_token, :presence => true
  validates :uid, :presence => true, :uniqueness => true, :numericality => true
  validates :provider, :format => {:with => /^facebook$/}

  has_many :created_events, :class_name => "Event", :foreign_key => "creator_id", :dependent => :destroy

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_login!
    redirect_to new_user_path unless signed_in?
  end

  def signed_in?
    current_user.present?
  end

  before_filter :require_login!

  private
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = current_user.created_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.new(params[:event])

    if @event.valid?
      callback = current_user.facebook.put_object('me', 'events', @event.to_facebook_params)

      @event.fb_id = callback["id"]
      @event.save

      render 'update'
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])

    if @event.acceptable_invites.any?
      render 'details' # table of friends
    else
      render 'empty'
    end
  end

  def update
    @event = Event.find(params[:id])

    @event.attributes = params[:event]
# ---- modified code from rake invites:send, need to process first batch
    fb = Koala::Facebook::GraphAPI.new(@event.creator.oauth_token)
    if @event.headcount > @event.acceptable_invites.attending.count
      spots_left = @event.headcount - @event.acceptable_invites.attending.count

      spots_left.times do |i|
        i -= 1
        if person = @event.acceptable_invites.pending[i]
          fb.put_connections(@event.fb_id, "invited", :users => person.fb_id)
          person.noreply!
        end
      end
    end
#----------------
    if @event.save
      render 'details'
    else
      redirect_to @event
    end
  end

  def destroy
    @event = Event.find params[:id]
    fb = Koala::Facebook::GraphAPI.new(@event.creator.oauth_token)
    callback = fb.rest_call("events.cancel", { eid: @event.fb_id, cancel_message: "", callback: "" })    
    if callback && @event.destroy
      redirect_to events_path
    else
      render(:text => 'Sorry, your event was not successfully deleted. Please try again.')
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login!, :only => [:create]

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login!

	def new
		render 'new', :layout => 'registration'
	end
	
	def edit
	  @user = current_user
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to signout_path
  end
end

app/helpers/acceptable_invites_helper.rb
module AcceptableInvitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper

  def event_length(event) # calculate length in minutes
    (event.end_datetime - event.start_datetime) / 60
  end

  def event_start_position(event)
    (event.start_datetime - (Time.now.midnight)) / 60 # + 9.hours
  end
end

app/views/events/_form.html.erb
<div id="events_form">
  <div id="form_header"><h4>Create New Event</h4></div>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="options">
    <div class="fields">
      <%= form_for(@event)  do |f| %>
      <%= f.text_field :name, :placeholder => "Name:" %><br />
      <%= f.text_area :description, :placeholder => "Details:" %><br />
      <%= f.text_field :location, :placeholder => "Where:" %><br />

      <ul id="options">
        <li><%= f.label 'From' %></li>
        <li><%= f.datetime_select :start_datetime, :ampm => true, :minute_step => 15 %></li>
        <li><%= f.label 'To' %></li>
        <li><%= f.datetime_select :end_datetime, :ampm => true, :minute_step => 15 %></li>
        <li>Headcount Goal <%= f.number_field :headcount, :placeholder => "Headcount Goal" %></li>
        <li>Invitations expire after <%= f.number_field :expired_time %> minutes</li>
      </ul>

    </div><!-- .fields -->
  </div><!-- .options -->

    <div id="form_footer">
      <%= f.submit %>
      <%= link_to 'Cancel', events_path %>
    </div>
  <% end %>
</div>

app/views/events/details.html.erb
<script type="text/javascript">
  $(document).on('fbInit', function() {
    Facebook.getFriendsData(function(response) {
      console.log(response.data);
      for(var i = 0;i < response.data.length;i++) {
        $('#facebook_ids').append(Facebook.createFriendCheckbox(response.data[i]));
      }
    });
  });
</script>

<div id="event_status">
  <div id="title">
    Event Status
  </div>
  <div id="event_friends">
    <h3>Going</h3>
    <div>
      <ul>
        <% @event.acceptable_invites.attending.each do |invitee| %>
          <li><%= invitee.name %></li>
        <% end %>
      </ul>
    </div>
    <h3>Not Going</h3>
    <div>
      <ul>
        <% @event.acceptable_invites.declined.each do |invitee| %>
          <li><%= invitee.name %></li>
        <% end %>
      </ul>
    </div>
    <h3>Maybe</h3>
    <div>
      <ul>
        <% @event.acceptable_invites.maybe.each do |invitee| %>
          <li><%= invitee.name %></li>
        <% end %>
      </ul>
    </div>
    <h3>No Reply</h3>
    <div>
      <ul>
        <% @event.acceptable_invites.noreply.each do |invitee| %>
          <li><%= invitee.name %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <ul id="event_details">
    <li><h6>What:</h6> <%= @event.name %></li>
    <li><h6>When:</h6> <%= @event.start_datetime.localtime.strftime('%l:%M%p on %d %b %Y') %></li>
    <li><h6>Until:</h6> <%= @event.end_datetime.localtime.strftime('%l:%M%p on %d %b %Y') %></li>
    <li><h6>Where:</h6> <%= @event.location %></li>
    <li><h6>Attendees:</h6> <%= @event.acceptable_invites.attending.count %></li>
    <li><h6>Description: </h6> <%= @event.description %></li>
    <li class="event_edit_links"><%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Delete Event', @event, method: :delete, data: { confirm: 'Really delete?' } %> |
    <%= link_to 'Home', events_path %></li>
  </ul>
</div> <!-- #event_status -->

app/views/events/empty.html.erb
<p>This event is empty, you never added any friends to this event</p>
<%= link_to 'Delete Event', @event, method: :delete, data: { confirm: 'Really delete?' } %>

app/views/events/index.html.erb
<ul>
<% @events.each do |event| %>
  <li><%= link_to event.name, event %></li>
<% end %>
</ul>

<%= link_to "Add event", new_event_path  %>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/update.html.erb
<%= form_for(@event) do %>
<div id="foobar"></div>
  <%= submit_tag("Submit") %>
<% end %>

<script type="text/javascript">
$(document).on('fbInit', function() {
  Facebook.getFriendsData(function(response) {
    console.log(response.data);
    for(var i = 0;i < response.data.length;i++) {
      $('#foobar').append(Facebook.createFriendCheckbox(response.data[i]));
    }
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Mouse+Memoirs' rel='stylesheet' type='text/css'>
  <title>Squirrely</title>
  <script type="text/javascript">
    var facebook_app_id = "<%= OMNI_SETTINGS['APP_ID'] %>";
  </script>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!-- "http://mbostock.github.com/d3/d3.v2.js", -->
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="fb-root"></div>
  <script type="text/javascript">
    window.fbAsyncInit = function() {
      // init the FB JS SDK
      FB.init({
        appId      : facebook_app_id, // App ID from the App Dashboard
        status     : true, // check the login status upon init?
        cookie     : true // set sessions cookies to allow your server to access the session?
      });
      // Additional initialization code such as adding Event Listeners goes here

      FB.getLoginStatus(function() {
        $(document).trigger('fbInit');
      });
    };

    (function(d, debug){
       var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement('script'); js.id = id; js.async = true;
       js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
       ref.parentNode.insertBefore(js, ref);
     }(document, /*debug*/ false));
  </script>
  <div id="header">
    <h1 id="title">Squirrely</h1>
    <div id="auth">
        <% if current_user %>
           Welcome, <strong><%= current_user.name %></strong><br />
          <%= link_to "Settings", settings_path %> &middot;
          <%= link_to "Log out", signout_path %>
        <% else %>
          <%= link_to "Log in", "/auth/facebook" %>
        <% end %>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
    </div> <!-- # auth -->
  </div>   <!-- # header -->
  <%= yield %>
</body>
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Glegoo|Mouse+Memoirs' rel='stylesheet' type='text/css'>
  <title>Squirrely</title>
  <script type="text/javascript">
    var facebook_app_id = "<%= OMNI_SETTINGS['APP_ID'] %>";
  </script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- "http://mbostock.github.com/d3/d3.v2.js", -->
    <%= csrf_meta_tags %>

</head>
  <body>
    <div id="fb-root"></div>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Delete Account', delete_account_path, data: { confirm: 'Are you sure?  All your Facebook events managed by Squirrely will be removed.' } %>

app/views/users/new.html.erb
  <div id="wrapper">
	<img id="bg" />
    <div id="content">
      <div id="site_slogan">
        <h1>Squirrely</h1>
          <%= link_to '', '/auth/facebook', :class => 'fb-connect-button' %>
          <span id="copy"></span><br/>
      </div>
    </div>
  </div>
  <!-- The container for the background-image -->

  <!-- The container for the grid on top of the background-image -->
  <div id="bg_grid">
  </div>

<script type="text/javascript" src="jquery-1.8.3.min.js"></script>

<script type="text/javascript">
  var images = new Array();
  var copy = new Array();
  var iPrev = -1;
  var iRnd = -1;

  images[0] = "http://2.bp.blogspot.com/-B85dEhVnbRM/TfBXQr14BpI/AAAAAAAAAGw/kI-xZ_aGI7s/s1600/Clara%2527s+1st+birthday+party+BBQ.jpg";
  images[1] = "http://www3.pictures.zimbio.com/bg/Diego+Luna+Diego+family+lunch+C6sprqnkqucl.jpg";
  images[2] = "http://c365781.r81.cf2.rackcdn.com/datas/21263207/original/pearland_basket_ball.jpg";
  images[3] = "http://eptdesign.com/beta/wp-content/uploads/2011/08/EPT-picnic-077.jpg";
  images[4] = "http://4.bp.blogspot.com/-pwnKbcWWM3U/TwoKdlMTFBI/AAAAAAAAJUA/XvXMGse909g/s1600/blog+picnic+2.JPG";
  images[5] = "http://eptdesign.com/beta/wp-content/uploads/2011/08/EPT-picnic-083.jpg";
  images[6] = "http://www.prosperitycandle.com/wp-content/uploads/2012/06/PIcnic-1.jpg";

  copy[0] = "Turn Facebook friends into real friends.";
  copy[1] = "Quickly create Facebook events.";
  copy[2] = "Get RSVP email notifications.";
  copy[3] = "Turn Facebook friends into real friends.";
  copy[4] = "Easily manage events.";
  copy[5] = "Turn Facebook friends into real friends.";
  copy[6] = "Easily manage events.";

  $(document).ready(function() {

    /* Define the function that triggers to fade in the background as soon as the image has loaded */
    $("img#bg").load(function()
      {
        /* Fade in during 4 seconds */
        $("img#bg").fadeTo(4000,1);

        /* Animate the picture description */
          setTimeout(function() {
            $("#site_slogan").animate(100) }, 500);
            // $("#site_slogan").animate({right: '0'}, 100) }, 500);

        /* Set the timeout to fade out the image and the description after 10 seconds*/
          setTimeout(function() {
            $("#site_slogan").animate(100);
            $("img#bg").fadeOut(4000);

              /* Load the next image after 4 seconds */
              setTimeout(LoadImages,4000);
            }
            ,5000);
      })

    /* Start the slideshow one second after the page is ready */
    setTimeout(LoadImages,1000);
    });

    function LoadImage(iNr) {

    /* Assign the new image to the background */
    $("img#bg").attr("src", images[iNr]);
    $("#copy").html(copy[iNr]);

    };

    function LoadImages() {

      /* Select a random image number and make sure this is not equal to the previous image */
      while(iPrev == iRnd)
      {
        iRnd = Math.floor(Math.random()*images.length);
      }

      /* Show the selected image */
      LoadImage(iRnd);
      iPrev = iRnd;

    };
</script>